### ISSUE TITLE
MVP Checklist

### ISSUE THREAD

**Issue by MichaelNash1990** [MichaelNash1990/VotingWithReason#1]
- [ ] Add Ricardian Contract to the smart contract
- [ ] Complete Smart Contract
- [ ] Create basic website
